spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/spring-mybatis?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpth:mapper/*.xml
  type-aliases-package: com.han.springbootmybatisplus2.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      han:
        springbootmybatisplus2:
          mapper: debug